### ISSUE TITLE
Anlaufstellen

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#14]
wichtige Anlaufstellen:
* InfoPoint
* Tagungsbüro
* Orgabüro
* Depp vom Dienst
* ...

**Comment by TomTomRixRix** [comment]
Erste Fassung in Commit ec9ed50ed796b854ab054bfc3e820426794dfc2e on branch `survive` umgesetzt. Es fehlen noch Telefonnummern und Öffnungszeiten

**Comment by jgraefje** [comment]
Raumnummern müssen teilweise noch ergänzt werden.
