### ISSUE TITLE
Kommunikationskanäle

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#15]
* Telegram
* Mailingliste
* Website
* Engelsystem
* Pads

**Comment by TomTomRixRix** [comment]
Erste Versuche in Commit 43eab3b333106ba480fbdbd111fc5a02c17e30b9 auf branch `survive` umgesetzt

**Comment by jgraefje** [comment]
Ein paar Ergänzungen gemacht, ist aber noch nicht vollständig, weil Mailadressen und Räume noch nicht endgültig feststehen.
