### ISSUE TITLE
Exkursionen, Stadtführung etc.

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#16]
*  Schlossbeleuchtung erwähnen
* Texte von Exkursionleitenden können übernommen werden, wenn sie ein einheitliches Format bekommen
* bei der Stadtführung könnten Christian und Dannah helfen

**Comment by mathivierpunktnull** [comment]
Treffpunkt und Uhrzeiten Infos fehlen noch
