### ISSUE TITLE
ÖPNV

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#17]
Moonliner, Bismarkplatz als zentraler Knotenpunkt, Strecke vom und zum Hauptbahnhof, Karten mit häufigen Abfahrtstellen, häufig genutzte Linien
nextbike?

**Comment by ChrisBtt** [comment]
Nextbike! www.vrnnextbike.de

**Comment by ChrisBtt** [comment]
branch created "mobil" and document created "mobilitaet.tex"
