### ISSUE TITLE
Physik Fakultät

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#19]
Die Fakultät und ihre Forschungsgruppen vorstellen. Vielleicht hier das berühmte Kolloqium mit Ort und Zeit erwähnen. HGSFP erwähnen.

**Comment by mathivierpunktnull** [comment]
Außerdem noch ein kleiner, hoffentlich nicht zu langweiliger, historischer Ausflug
