### ISSUE TITLE
Gebäude-Raumplan

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#20]
vom KIP und PI mit AK Raum Nummern, Tagungsbüro, ewigem Frühstück etc.
(Mathematikon?)

**Comment by ChrisBtt** [comment]
die Toiletten sind sicher auch noch wichtig. Auch wenn man das immer vergisst, die braucht man auch!

**Comment by TomTomRixRix** [comment]
Plenen: HS1
AKs: Seminarräume
Ewiges Frühstück: Goldener Käfig PI
Tagungsbüro: ?
Orga Büro: FS Raum PI
Toiletten solltest du vllt markieren
Mensa: INF 304
Grillplatz: hinter der Chemie

**Comment by henrixapp** [comment]
welche chemie? 252?

**Comment by TomTomRixRix** [comment]
Am besten mal Sebbo fragen, der kümmert sich ums Grillen. Aber ich vermute, dass damit hinter der Reinen Mathe gemeint ist, da wo das Grillen nach den Vollversammlungen stattfand.

**Comment by mathivierpunktnull** [comment]
Nach meinem Stand wird wahrscheinlich nicht wie bei der Vollversammlung gegrillt (nerviges Prozedere mit Bau und Liegenschaften), sondern zwischen PI und KIP, aber lieber die Verantwortlichen fragen.

**Comment by TomTomRixRix** [comment]
Erste Version mit #51 erstellt. Soll da noch eine Legende mit dazu?
