### ISSUE TITLE
Campusplan

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#21]
mit Schlafplätzen (Jugendherberge + Notunterkünfte), Essen, KIP, PI, Bushaltestelle, Mensa, etc.

kommt auf die hintere Innenseite des Mantelbogens. Dafür gibt es bereits einen Branch `mantelbogen` mit der `mantelbogen.tex`

**Comment by TomTomRixRix** [comment]
Parkplätze gibt es in geringer Anzahl bei der DJH

**Comment by henrixapp** [comment]
Mögliche Idee: QR-Codes für kip und djh abdrucken

**Comment by mathivierpunktnull** [comment]
Ein Großteil der Leute kommt wohl in den Stuwe Wohnheimen im Feld unter, hoffentlich steht das bis nächste Woche fest.

**Comment by mathivierpunktnull** [comment]
Es handelt sich um die Gebäude 693, 694, 695 und 696.

**Comment by TomTomRixRix** [comment]
Wie ist der Stand von der Karte? Fehlen noch Informationen bezüglich Notunterkünften, Mensa, Kneipen etc.?
