### ISSUE TITLE
Begrüßungstext von der Orga

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#25]
Nette Worte am Anfang

**Comment by jgraefje** [comment]
So habe jetzt einen Entwurf commited. Beurteile bitte mal jemand, ob das etwas zu savage ist und da ZaPFika in Tränen ausbrechen. Die Triumphiratten können damit grundsätzlich leben, aber ob das iwie lustig ist, was ich da produziert habe, weiß ich noch nicht genau.
