### ISSUE TITLE
Danksagungen

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#26]
Helfer, Fakultät, Unterstützer

**Comment by jgraefje** [comment]
Habe so ein paar relativ belanglose Aufzählungen gemacht; sind bis jetzt relativ wenige, weil wir mit wenigen Leuten Kontakt hatten, denen ich auch tatsächlich danken will. Gerade wenn ihr noch jemand wisst, dem wir persönlich danken sollten, ergänzt das gerne.
