### ISSUE TITLE
Kneipenauswahl

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#28]
Liste mit Kneipen, die man in Heidelberg gesehen haben sollte. Am besten mit 3 netten Sätzen, wofür die Kneipe jeweils bekannt ist. Vielleicht auch eine Karte mit Pins oder Nummer, wo welche Kneipe liegt.

Das kann man dann auch gleich fürs [Ersti-Info](https://github.com/FachschaftMathPhys/Ersti-Info/issues/185) übernehmen

**Comment by ChrisBtt** [comment]
Branch: kneipen

Text und Karte aus dem Ersti-Info kopiert und zum Laufen gebracht
Kneipen-Auswahl muss noch validiert werden

**Comment by TomTomRixRix** [comment]
Man kann ggf. nochmal die Liste durchgehen und überarbeiten, aber fürs erste passt das so. Ich habe das Issue der Übersichtlichkeit halber mal geschlossen, wenn man noch weiter dran arbeiten möchte, kann man ja ein neues mit einer genaueren Beschreibung aufmachen ;)
