### ISSUE TITLE
Fachschaft

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#29]
Vorstellung unserer Fachschaft

**Comment by TomTomRixRix** [comment]
assigned to Irina

**Comment by TomTomRixRix** [comment]
Die Uni Heidelberg hat die größte Physikfakultät in Deutschland, in der Fachschaft engagieren sich davon jedoch nur wenige :( 
Aus diesem Grund gibt es die gemeinsame Fachschaft MathPhysInfo. Fachlich sind wir getrennt, aber alle anderen Angelegenheiten wie Räumlichkeiten und Freizeitveranstaltungen teilen wir. Dazu zählt auch die diesjährige ZaPF, wundert euch also nicht wenn ihr unter den Helfern den ein oder anderen Mathematiker und Informatiker findet.
Wir sitzen wie Fachschaften das so tun in einigen Gremien, veranstalten den Vorkurs der MathInffakultät und helfen bei dem der Physikfakultät. Außerdem haben wir wöchentlich mehr oder weniger sinnvolle Sitzungen und irgendwer ist eigentlich immer im Fachschaftsraum, weswegen dieser auch schon als 20-Personen-WG bezeichnet wurde.
Wir können aber nicht nur arbeiten, sondern gleichzeitig auch feiern, denn wir organisieren die größte Studiparty Heidelbergs, zusammen mit der Fachschaft Theologie. Um gleich mal mit den Gerüchten aufzuräumen, diese Kombination ist nicht durch den hohen Frauenanteil der Theologen entstanden.
Wer es etwas gemütlicher mag kommt zu der monatlichen Cafétenfete oder zu den Spieleabenden, und wer dann noch mehr Zeit mit der Fachschaft verbringen möchte, begleitet uns auf das Fachschaftswochenende in den Odenwald, um dort zu diskutieren und einander besser kennenzulernen.
Falls ihr noch mehr zu uns und was wir so machen, wissen wollt, findet ihr das auf unserer Website und Social Media.

**Comment by ChrisBtt** [comment]
"Die Uni Heidelberg hat die größte Physikfakultät Deutschlands, trotzdem gelingt es uns Fachschaftlern immer wieder neue Veranstaltungen für alle Studierende zu planen. Um den Organisations- ebenso, wie den Verwaltungsaufwand trotzdem möglichst gering zu halten, haben sich die Studierendenschaften Mathematik, Informatik und Physik zu der Fachschaft MathPhysInfo zusammen geschlossen."
Wäre vielleicht etwas ansprechender ;)

**Comment by TomTomRixRix** [comment]
Eingebaut mit Commit 3bf7cd0062315f10545471e1ed3f1cc34dc37bfe

Außerdem habe ich das FS Logo und die Social Media Handles eingefügt
