### ISSUE TITLE
Not/Gemeinschaftsunterkünfte

### ISSUE THREAD

**Issue by mathivierpunktnull** [FachschaftMathPhys/zapf-tagungsheft#41]
Da wir jetzt die Lage endgültig bestätigt bekommen haben, 693, 694, 695 und 696 kann das auch endlich ins Tagungsheft, dort sollte man dann auch auf die Hausordnung hinweisen. Die Lage mit den Duschen ist noch nicht geklärt und kann daher wahrscheinlich nicht mit ins Tagungsheft.

**Comment by TomTomRixRix** [comment]
@mathivierpunktnull Wer kümmert sich darum, dass ein Text dazu ins Tagungsheft kommt? Du oder vielleicht @ChrisBtt?

**Comment by mathivierpunktnull** [comment]
Ich schreibe ein paar Sätze dazu. Die Notunterkünfte in der Map zu verzeichnen muss jemand anders machen
