### ISSUE TITLE
Einheitliches Gendern

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#57]
Wollen wir das Tagungsheft noch einheitlich gendern? 
Ich würde vorschlagen, dies nach den ZaPF Gender Regeln zu tun, also mit -ikon und -ika

**Comment by mathivierpunktnull** [comment]
Soweit aus meiner Sicht in Ordnung gestellt, man muss da aber auch nicht faschistoid sein, die Geschäftsordnung nutzt auch männliche wie weibliche Form und die kombinierte Fassung mit *.
