### ISSUE TITLE
Liedtexte

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#6]
Folgende Lieder sollen in das Tagungsheft aufgenommen werden:

- [x] Blau wie das Meer - ZaPF Edition
- [ ] What does the Duck say
- [x] Insel mit zwei Bergen
- [x] Ente, Ente Ente (Dance-mix)
- [x] Ich und mein Pony
- [ ] Wenn ich den See seh
- [ ] Ihr wart noch nie im Siegerland
- [ ] Plenum
- [ ] Der Steiger
- [ ] Einheitsfrontlied
- [ ] Abend in der Stadt
- [ ] Rauch-Haus-Lied
- [ ] Die Internationale
- [ ] Alles nur geklaut
- [ ] Schwarz zu blau
- [ ] .... Vorschläge willkommen
- [x] Badnerlied
- [x] Ich hab mein :heart: in Heidelberg verloren
- [x] Reformgedicht von D. Grommes

**Comment by TomTomRixRix** [comment]
Vielleicht komponieren wir ja auch noch einen Heidelberger Song, der muss dann natürlich auch mit rein

**Comment by TomTomRixRix** [comment]
Man sollte ich auch noch ein paar Gedanken um ein einheitliches Design der Liedtexte machen. Aktuell gibt es eine `lied` Umgebung, welche zwei Argumente (Title, Sänger/Gruppe) annimmt. 

Zu klärende Fragen:
* Will man den Text immer zentriert haben?
* Will man den Text immer in tt gesetzt haben?
* Will man Refrains und Anmerkungen immer kursiv haben?
* Wann werden Seiten umgebrochen?

**Comment by mathivierpunktnull** [comment]
Man vergesse nicht das Reform-Gedicht von Dieter Gromes, man sollte ihm deswegen auch mal eine Mail schreiben (http://www.thphys.uni-heidelberg.de/~gromes/reformgedicht.pdf)

**Comment by TomTomRixRix** [comment]
Herr Gromes hat seine Zustimmung erteielt
