### ISSUE TITLE
Sponsoren

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/zapf-tagungsheft#9]
mit Logo auf eine Seite
* HGSFP mit Logo
* Klaus-Tschira-Stiftung
* Haereus Stiftung
* StuRa Logo
* VolumeGraphics (+ extra Seite: siehe Mail vom 14.3.)
* Fakultät Physik
* DPG
* papercraft
* Locomore
* Lehmkuhl Feine Weine

**Comment by TomTomRixRix** [comment]
@jgraefje Fehlen da noch Institutionen/Sponsoren?

**Comment by TomTomRixRix** [comment]
aktuell sieht die Seite so aus:
![grafik](https://user-images.githubusercontent.com/13121269/37560288-c561a756-2a35-11e8-9272-66206a548ebd.png)

**Comment by TomTomRixRix** [comment]
Campusheld und Springer vielleicht noch?
Und was ist mit dem StuWe und anderen Dienstleistern?

**Comment by TomTomRixRix** [comment]
Und ggf, Pfeiffer Vaccum

**Comment by jgraefje** [comment]
Ich würde rausnehmen:
-Feine Weine
Und ergänzen:
-Pfeiffer Vacuum
-StuWe
-Springer

Rest passt, glaube ich
